name: Run Google Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libboost1.74-all-dev=1.74.0-14ubuntu3 \
          build-essential \
          cmake=3.22.1-1ubuntu1.22.04.2 \
          libssl-dev=3.0.2-0ubuntu1.18 \
          libpq-dev=17.2-1.pgdg22.04+1 \
          pkg-config \
          rapidjson-dev=1.1.0+dfsg2-7 \
          libyaml-cpp-dev=0.7.0+dfsg-8build1 \
          libhiredis-dev=0.14.1-2

    - name: Cache build directories
      uses: actions/cache@v3.3.1
      with:
        path: |
          build/_deps
          ~/.cache/pip
        key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Cache build artifacts
      uses: actions/cache@v3.3.1
      with:
        path: |
          build/CMakeFiles
          build/*/CMakeFiles
          build/*/*.a
          build/*/*.so
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build project
      run: |
        cd scripts
        chmod +x *.sh
        ./build.sh --debug --clean
      shell: bash

    - name: Run tests
      run: |
        cd scripts
        ./run_tests.sh