name: Run Google Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt install -y \
          libboost1.74-all-dev \
          build-essential \
          cmake \
          libssl-dev \
          libpq-dev \
          pkg-config \
          rapidjson-dev \
          libyaml-cpp-dev \
          libhiredis-dev

    - name: Cache build directories
      uses: actions/cache@v3
      with:
        path: |
          build/_deps
          ~/.cache/pip
        key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          build/CMakeFiles
          build/*/CMakeFiles
          build/*/*.a
          build/*/*.so
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-
          
    - name: Build project
      run: |
        cd scripts
        chmod +x *.sh
        ./build.sh --debug --clean
      shell: bash

    - name: Run tests
      run: |
        cd scripts
        ./run_tests.sh